---
- hosts: all
  tasks:
  - import_tasks: tasks/000-default-packages.yml
  - import_tasks: tasks/020-time.yml
  - import_tasks: tasks/100-zsh.yml
  - import_tasks: tasks/110-vim.yml
  - import_tasks: tasks/120-tmux.yml
  - import_tasks: tasks/130-docker.yml
  - import_tasks: tasks/140-git.yml
  - import_tasks: tasks/200-python.yml
  - import_tasks: tasks/210-golang.yml
  - import_tasks: tasks/220-nodejs.yml
  - import_tasks: tasks/230-clang.yml
  - import_tasks: tasks/240-shell.yml
  - import_tasks: tasks/250-java.yml
  - import_tasks: tasks/300-kubernetes.yml
  - import_tasks: tasks/400-ai-tools.yml
  - import_tasks: tasks/900-rc.yml
