#!/usr/bin/env bash
set -euo pipefail

# Install packages, if dependencies are not installed.
SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"
# shellcheck source=install-ansible
source "$SCRIPT_DIR/install-ansible"

ansible-playbook -i "localhost," --connection=local "$SCRIPT_DIR/playbook.yml"
