#!/usr/bin/env bash
set -euo pipefail

# Check if Ansible exists
command -v ansible > /dev/null ||
  (echo "'ansible' command not found. Use one of the following commands to install Ansible:
  * pip install ansible
  * sudo add-apt-repository --yes --update ppa:ansible/ansible && sudo apt install ansible
  * brew install ansible"; exit 1)

SCRIPT_DIR="$(dirname "${BASH_SOURCE[0]}")"

# Enable Ansible logging
mkdir -p log
ANSIBLE_LOG_PATH="$SCRIPT_DIR/log/log.$(date +%Y%m%d%H%M%S)"
export ANSIBLE_LOG_PATH

ansible-playbook -i "localhost," --connection=local "$SCRIPT_DIR/playbook.yml" "$@"
