#!/usr/bin/env bash

set -euo pipefail

# Install packages, if dependencies are not installed.
install_sshpass () {
    echo "It requires to install 'sshpass'."
    echo "Installing 'sshpass' ..."
    sudo apt update
    sudo apt -y install ssh && \
        echo "'sshpass' installation complated."
}

command -v sshpass > /dev/null || install_sshpass

source install-ansible


# Pull docker image for test
# * Dockerhub: devinjeon/vin.sh-test(will be made as a Dockerfile later)
image='devinjeon/vin.sh-test'

if [ -z "$(docker images -q "$image")" ]; then
    echo "Pulling docker image: $image ..."
    docker pull "$image"
fi

# Remove docker container already running
container='vin.sh-test'
if [ -n "$(docker ps -q -f name="$container")" ]; then
    echo "Removing docker container already running: $container ..."
    docker rm -f "$container" 1> /dev/null
fi

port=2223
# Run docker
echo "Run docker container: $container ..."
docker run -tid --name "$container" -p "$port":22 "$image" 1> /dev/null

# Execute ansible playbook

# Ansible fails with following error in container
# stderr: "/bin/sh: 1: /usr/bin/python: not found"
# Replace python interpreter.
# "/usr/bin/python"(default) to "/usr/bin/env python3"

ansible-playbook -i "localhost," -e "\
    ansible_port='$port'\
    ansible_user='ubuntu'\
    ansible_ssh_pass='vin.sh-test'\
    ansible_python_interpreter='/usr/bin/python3'"\
    "playbook.yml"
