---
- name: Install default packages (step 1/5)
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: latest
  vars:
    packages:
      - bash-completion
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - git
      - gnupg
      - htop
      - jq
      - language-pack-ko
      - libcurl4-gnutls-dev
      - libffi-dev
      - libldap2-dev
      - libpq-dev
      - libreadline-dev
      - libsasl2-dev
      - libsqlite3-dev
      - libssl1.0-dev
      - libxml2-dev
      - libxslt1-dev
      - openssl
      - python-dev
      - python-pip
      - python-setuptools
      - python3
      - python3-dev
      - python3-pip
      - python3-venv
      - rdate
      - tree
      - yum
      - zip
  become: true

- name: Install python packages (step 2/5)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - awscli
    - mycli
  become: true

- name: Install homebrew (step 3/5)
  shell: "/bin/bash -c \"NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""

- name: Update homebrew (step 4/5)
  homebrew:
    update_homebrew: yes

- name: Create homebrew rc symbolic link (step 5/5)
  file:
    src: "{{ playbook_dir }}/rc/homebrew"
    dest: ~/.rc/homebrew
    state: link
    force: true
