---
- name: Install default packages (step 1/2)
  homebrew:
    name:
      - bash-completion
      - cmake
      - curl
      - git
      - htop
      - jq
      - openssl
      - rdate
      - tree
      - zip
      - coreutils
      - gnu-sed
      - gnu-tar
      - gh
    state: latest

- name: Install python-pip - Download get-pip.py
  get_url:
    url: https://bootstrap.pypa.io/get-pip.py
    dest: /tmp/get-pip.py
    mode: 0440

- name: Install python-pip
  shell: "python /tmp/get-pip.py; python3 /tmp/get-pip.py"

- name: Install python packages (step 2/2)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - awscli
    - mycli
  become: true
