---
- name: Install default packages (step 1/2)
  homebrew:
    name:
      - bash-completion
      - cmake
      - curl
      - git
      - htop
      - jq
      - openssl
      - rdate
      - tree
      - zip
      - coreutils
      - gnu-sed
      - gnu-tar
    state: latest

- name: Install python packages (step 2/2)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - awscli
    - mycli
  become: true
