---
- name: Install default packages
  apt:
    name: "{{ packages }}"
    update_cache: true
    state: latest
  vars:
    packages:
      - bash-completion
      - build-essential
      - ca-certificates
      - cmake
      - curl
      - git
      - gnupg
      - htop
      - jq
      - language-pack-ko
      - libcurl4-gnutls-dev
      - libffi-dev
      - libldap2-dev
      - libpq-dev
      - libreadline-dev
      - libsasl2-dev
      - libsqlite3-dev
      - libssl-dev
      - libxml2-dev
      - libxslt1-dev
      - openssl
      - python-dev
      - python-pip
      - python-setuptools
      - python3
      - python3-dev
      - python3-pip
      - rdate
      - tmux
      - tree
      - yum
      - zip
  become: true

- name: Install python packages
  pip:
    name: "{{ packages }}"
  vars:
    packages:
    - awscli
  become: true
