---
- name: Install default packages (step 1/3)
  homebrew:
    name:
      - bash-completion
      - cmake
      - curl
      - git
      - htop
      - jq
      - openssl
      - rdate
      - tree
      - zip
      - coreutils
      - gnu-sed
      - gnu-tar
    state: latest
    update_homebrew: yes

- name: Install python packages (step 2/3)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - awscli
    - mycli
  become: true

- name: Update homebrew (step 3/3)
  homebrew:
    update_homebrew: yes
    path: /home/linuxbrew/.linuxbrew/bin
