---
- name: Install epel release (step 1/13)
  yum:
    name: epel-release
  become: true

- name: Install default packages (step 2/13)
  yum:
    name: "{{ packages }}"
    update_cache: true
    state: latest
  vars:
    packages:
      - bash-completion
      - ca-certificates
      - cmake
      - curl
      - git
      - gnupg
      - htop
      - jq
      - openssl
      - python-devel
      - python-pip
      - python-setuptools
      - python3
      - python3-devel
      - python3-pip
      - rdate
      - tree
      - zip
      - cargo
  become: true

- name: Upgrade PIP (step 3/13)
  pip:
    name: pip
    extra_args: -U
    executable: pip3
  become: true

- name: Install python packages (step 4/13)
  pip:
    name: "{{ packages }}"
    executable: pip3
  vars:
    packages:
    - awscli
    - mycli
    - virtualenv
  become: true

- name: Make rc directory
  file:
    path: ~/.rc
    state: directory

- name: Install homebrew (step 3/5)
  shell: "/bin/bash -c \"NONINTERACTIVE=1 $(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""

- name: Create homebrew rc symbolic link (step 5/5)
  file:
    src: "{{ playbook_dir }}/rc/homebrew"
    dest: ~/.rc/homebrew
    state: link
    force: true

- name: Update homebrew (step 4/5)
  homebrew:
    update_homebrew: yes

- name: Install cURL (step 5/13)
  get_url:
    url: https://github.com/moparisthebest/static-curl/releases/download/v7.77.0/curl-amd64
    dest: /usr/bin/curl
  become: true

- name: Install Git - ensure temporary directory (step 6/13)
  file:
    path: /tmp/git
    state: directory
  become: true

- name: Specify git filename (step 7/13)
  command: echo "2.32.0"
  register: version

- name: Install Git - Download and unarchive (step 8/13)
  unarchive:
    src: "https://mirrors.edge.kernel.org/pub/software/scm/git/git-{{ version.stdout }}.tar.gz"
    dest: /tmp/git
    remote_src: true
  become: true

- name: Install Git - Compile (step 9/13)
  shell: "make configure \
          && ./configure --prefix=/usr/local \
          && make install"
  args:
    chdir: "/tmp/git/git-{{ version.stdout }}/"
  become: true

- name: Create git symbolic link (step 10/13)
  file:
    src: "/usr/local/bin/git"
    dest: /usr/bin/git
    state: link
    force: true
  become: true

- name: Install homebrew (step 11/13)
  shell: "/bin/bash -c \"$(/bin/curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)\""

- name: Set env for homebrew (step 12/13)
  shell: "/home/linuxbrew/.linuxbrew/bin/brew shellenv > /home1/irteamsu/.rc/brewenv"

- name: Install brew packages (step 13/13)
  shell: "source /home1/irteamsu/.rc/brewenv && brew install {{ ' '.join(packages) }}"
  vars:
    packages:
      - gcc
      - fzf
      - kubectl
      - kubectx
      - k9s
      - minikube
      - kube-ps1
