---
- name: Make rc directory
  file:
    path: ~/.rc
    state: directory

- name: Create gitenv symbolic link
  file:
    src: "{{ playbook_dir }}/rc/gitenv"
    dest: ~/.rc/gitenv
    state: link
    force: true

- name: Create gitalias symbolic link
  file:
    src: "{{ playbook_dir }}/rc/git-aliases"
    dest: ~/.git-aliases
    state: link
    force: true

- name: Create cargorc symbolic link
  file:
    src: "{{ playbook_dir }}/rc/cargorc"
    dest: ~/.rc/cargorc
    state: link
    force: true
