---
- name: Set KST timezone
  file:
    src: /usr/share/zoneinfo/Asia/Seoul
    dest: /etc/localtime
    state: link
    force: true
  become: true

- name: Add cronjob to sync time
  cron:
    name: "timesync daily"
    special_time: daily
    job: "sudo rdate -s time.bora.net"
