---
- name: Install shellcheck - download (step 1/4)
  unarchive:
    src: https://storage.googleapis.com/shellcheck/shellcheck-latest.linux.x86_64.tar.xz
    dest: /tmp/
    remote_src: true

- name: Install shellcheck - Copy shellcheck to /usr/local/bin/ (step 2/3)
  shell: cp -f /tmp/shellcheck-latest/shellcheck /usr/local/bin/

- name: Install shellcheck - Remove /tmp/shellcheck (step 3/3)
  file:
    path: /tmp/shellcheck-latest
    state: absent
