---
- name: Install Oh My Zsh - install zsh (step 1/4)
  apt:
    name: zsh
    update_cache: yes
    state: latest
  become: true

- name: Install Oh My Zsh - get current user name (step 2/4)
  shell: whoami
  register: username

- name: Install Oh My Zsh - set default shell to zsh (step 3/4)
  user:
    name: "{{ username.stdout }}"
    shell: /usr/bin/zsh
  become: true

- name: Install Oh My Zsh - install oh-my-zsh (step 4/4)
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
