- name: Install tmux (step 1/5)
  homebrew:
    name:
      - tmux
      - fpp
    state: present

- name: Install tmux dependencies (step 1/6)
  yum:
    name: "{{ packages }}"
    state: latest
  vars:
    packages:
      - libevent-devel
      - ncurses-devel
      - glibc-static
  become: true

- name: Install tmux - Create tmux.conf symbolic link (step 2/5)
  file:
    src: "{{ playbook_dir }}/rc/tmux.conf"
    dest: ~/.tmux.conf
    state: link
    force: true

- name: Install tmux - Create tmuxenv symbolic link (step 4/6)
  file:
    src: "{{ playbook_dir }}/rc/tmuxenv"
    dest: ~/.rc/tmuxenv
    state: link
    force: true

- name: Install tmux - install tmux plugin manager(tpm) (step 5/6)
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: ~/.tmux/plugins/tpm

- name: Install tmux - install tmux plugins (step 6/6)
  shell: "~/.tmux/plugins/tpm/bin/install_plugins \
          && ~/.tmux/plugins/tpm/bin/update_plugins all \
          && ~/.tmux/plugins/tpm/bin/clean_plugins"

- name: Install tmux - install kube-tmux  (step 3/5)
  git:
    repo: "https://github.com/jonmosco/kube-tmux.git"
    dest: ~/.tmux/kube-tmux
