---
- name: Install fpp - ensure temporary directory (step 1/7)
  file:
    path: /tmp/fpp
    state: directory

- name: Install fpp - Download and unarchive (step 2/7)
  unarchive:
    src: https://github.com/facebook/PathPicker/releases/download/0.9.2/fpp.0.9.2.tar.gz
    dest: /tmp/fpp
    remote_src: true

- name: Install fpp - Remove /usr/share/fpp if it exists (step 3/7)
  file:
    path: /usr/share/fpp
    state: absent
  become: true

- name: Install fpp - Copy fpp to /usr/share/fpp (step 4/7)
  copy:
    src: /tmp/fpp
    dest: /usr/share/
    mode: preserve
  become: true

- name: Install fpp - Create symbolic link (step 6/7)
  file:
    src: /usr/share/fpp/fpp
    dest: /usr/bin/fpp
    state: link
    force: true
  become: true

- name: Install fpp - Remove /tmp/fpp (step 7/7)
  file:
    path: /tmp/fpp
    state: absent
