- name: Install python virtualenvwrapper
  pip:
    name: virtualenvwrapper
  become: true

- name: Create directory for python virtualenvwrapper
  file:
    path: "{{ virtualenvwrapper_home }}"
    state: directory
    mode: 0755
