- name: Install python virtualenvwrapper - Install the package (step 1/2)
  pip:
    name: virtualenvwrapper
  become: true

- name: Install python virtualenvwrapper - Copy env file (step 2/2)
  file:
    src: "{{ playbook_dir }}/rc/virtualenvwrapperenv"
    dest: ~/.rc/virtualenvwrapperenv
    state: link
