- name: Install python virtualenvwrapper - install package(step 1/3)
  pip:
    name: virtualenvwrapper
  become: true

- name: Install python virtualenvwrapper - Copy env file (step 3/3)
  file:
    src: "{{ playbook_dir }}/rc/virtualenvwrapperenv"
    dest: ~/.rc/virtualenvwrapperenv
    state: link
