- name: Install tmux (step 1/5)
  apt:
    name: tmux
    state: latest
  become: true

- name: Install tmux - Create tmux.conf symbolic link (step 2/5)
  file:
    src: "{{ playbook_dir }}/rc/tmux.conf"
    dest: ~/.tmux.conf
    state: link

- name: Install tmux - Create tmuxenv symbolic link (step 3/5)
  file:
    src: "{{ playbook_dir }}/rc/tmuxenv"
    dest: ~/.rc/tmuxenv
    state: link

- name: Install tmux - install tmux plugin manager(tpm) (step 4/5)
  git:
    repo: "https://github.com/tmux-plugins/tpm.git"
    dest: ~/.tmux/plugins/tpm

- name: Install tmux - install tmux plugins (step 5/5)
  shell: "~/.tmux/plugins/tpm/bin/install_plugins \
          && ~/.tmux/plugins/tpm/bin/update_plugins all \
          && ~/.tmux/plugins/tpm/bin/clean_plugins"
