---
# Golang should be installed from https://golang.org/dl/go1.16.5.darwin-amd64.pkg

- name: Install GoLang - Copy golangenv file to set environments for Go (step 2/2)
  file:
    src: "{{ playbook_dir }}/rc/golangenv"
    dest: ~/.rc/golangenv
    state: link
    force: true
