---
# Node.js should be installed from https://nodejs.org/en/

- name: Create npm-global symbolic link
  file:
    src: "{{ playbook_dir }}/rc/npm-global"
    dest: ~/.rc/npm-global
    state: link
    force: true
