---
- name: Install tools for CLI environment - Install tools (step 1/2)
  homebrew:
    name:
      - ripgrep
      - fzf
    state: present

- name: Install tools for CLI environment - Create symlink rc file (step 2/2)
  file:
    src: "{{ playbook_dir }}/rc/fzf"
    dest: ~/.rc/100-fzf
    state: link
    force: true
