- name: Install Python environments - Copy env file (step 1/3)
  file:
    src: "{{ playbook_dir }}/rc/pythonenv"
    dest: ~/.rc/pythonenv
    state: link
    force: true

- name: Install Python environments - Install pyenv (step 2/3)
  brew:
    name: pyenv
    state: present

- name: Install Python environments - Install poetry (step 3/3)
  shell: "curl -sSL https://install.python-poetry.org | python3 -"
