- name: Install Python environments - Copy env file (step 1/6)
  file:
    src: "{{ playbook_dir }}/rc/pythonenv"
    dest: ~/.rc/pythonenv
    state: link
    force: true

- name: Install Python environments - Install pyenv (step 2/6)
  homebrew:
    name: pyenv
    state: present

- name: Install Python environments - Install poetry (step 3/6)
  shell: "curl -sSL https://install.python-poetry.org | python3 -"

- name: Install python formatter (step 4/6)
  pip:
    name: yapf
    executable: pip3
  become: true

- name: Install python formatter - Make yapf config dir (step 5/6)
  file:
    path: ~/.config/yapf
    state: directory

- name: Install python formatter - Create yapf default config symbolic link (step 6/6)
  file:
    src: "{{ playbook_dir }}/rc/yapf_config"
    dest: ~/.config/yapf/style
    state: link
    force: true
