- name: Install sdkman - Install sdkman
  shell: |
    curl -s "https://get.sdkman.io" | bash
  args:
    executable: /bin/bash
  register: sdkman_install
  changed_when: sdkman_install.stdout is search("All done!")
