# lazyshell
- name: Install lazyshell - Download lazyshell.zsh
  get_url:
    url: https://raw.githubusercontent.com/devinjeon/lazyshell/refs/tags/v0.1.0/lazyshell.zsh
    dest: ~/.lazyshell.zsh
    mode: '0644'

# kubectl-gpt
- name: Install kubectl-gpt - Tap devinjeon/kubectl-gpt (step 1/2)
  homebrew_tap:
    name: devinjeon/kubectl-gpt
    state: present

# brew install kubectl-gpt
- name: Install kubectl-gpt - Install tools (step 2/2)
  homebrew:
    name: kubectl-gpt
    state: present
