#!/usr/bin/env bash
export DEFAULT_GOPATH="$HOME/workspace/go"
export GOPATH="$DEFAULT_GOPATH"
export GOROOT=/opt/homebrew/Cellar/go/1.19/libexec
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin:$GOPATH/bin/darwin_amd64/

# in M1 Mac (arm64)
export GOARCH=amd64

setgopath() {
  TARGET_PATH="$1"
  if [ -z "$TARGET_PATH" ]; then
    export GOPATH="$PWD"
  else
    export GOPATH="$TARGET_PATH"
  fi
  echo "* Set GOPATH=$GOPATH"
}

resetgopath() {
  setgopath "$DEFAULT_GOPATH"
}
