#!/usr/bin/env bash

if [[ -e "$HOME/.gvm/scripts/gvm" ]]; then
  source "$HOME/.gvm/scripts/gvm"
fi

# Check if GVM is installed
if ! command -v gvm &> /dev/null; then
  # Detect operating system
  OS_TYPE="$(uname)"

  if [ "$OS_TYPE" = "Darwin" ]; then
    # If macOS, check if Go is installed
    if ! command -v go &> /dev/null; then
      echo "Go (Golang) is not installed."
      echo "Download Go from: https://go.dev/dl/"
      exit 1
    fi
  fi

  # Install GVM
  echo "GVM is not installed. Proceeding with installation..."
  bash < <(curl -s -S -L https://raw.githubusercontent.com/moovweb/gvm/master/binscripts/gvm-installer)
  source "$HOME/.gvm/scripts/gvm"
fi
