#!/usr/bin/env bash

# pyenv
export PYENV_ROOT="$HOME/.pyenv"
command -v pyenv 1>/dev/null 2>&1 ||
  export PATH="$PYENV_ROOT/bin:$PATH"
  eval "$(pyenv init -)"

alias pe='pyenv'

# poetry
export PATH="$HOME/.local/bin:$PATH"
