" setting for encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp949,latin1

syntax on " Enable highlighting syntax

set nocp " not compatible with `vi`
set hls " hightlight search keywords
set ruler " show current cursor location
set history=1000 " history of vim command
set expandtab " softtab(space)
set tabstop=4 " tab size
set sw=4 " tab size: shifting(`<<`, `>>`)
set sts=4 " tab size: shifting(`<<`, `>>`)
set autoindent
set backspace=indent,eol,start

hi Search ctermbg=4 ctermfg=15
hi Visual ctermbg=White ctermfg=Black

" Plugins
call plug#begin('~/.vim/plugged')

" For Git
Plug 'rhysd/committia.vim'
Plug 'hotwatermorning/auto-git-diff'

" NERDTree=<Leader>n
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }

" Asyncsearch=<Leader>ff
Plug 'eugen0329/vim-esearch'

" Command-T=<Leader>t
Plug 'wincent/command-t', {
    \   'do': 'cd ruby/command-t/ext/command-t && ruby extconf.rb && make'}

" Graph undo tree
Plug 'simnalamburt/vim-mundo'

" Show indent
Plug 'Yggdroot/indentLine'

" airline
Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'

" For Python
Plug 'fisadev/vim-isort'
" For Golang
Plug 'fatih/vim-go', { 'do': ':GoUpdateBinaries' }

" google/vimcodefmt
Plug 'google/vim-maktaba'
Plug 'google/vim-glaive'
Plug 'google/vim-codefmt'

" LSP
Plug 'prabirshrestha/vim-lsp'
Plug 'mattn/vim-lsp-settings'
Plug 'prabirshrestha/asyncomplete.vim'
Plug 'prabirshrestha/asyncomplete-lsp.vim'

" Other
Plug 'tpope/vim-commentary' " Add shortcut `gc[c]` to comment out
Plug 'sheerun/vim-polyglot' " Highlight many languages syntax
Plug 'dense-analysis/ale' " Asynchronous Lint Engine


call plug#end()

" =================
" google/vimcodefmt

autocmd FileType c,cpp,proto let b:codefmt_formatter='clang-format'
autocmd FileType vue,javascript,html,css,sass,scss,less,json let b:codefmt_formatter='prettier'
autocmd FileType python let b:codefmt_formatter='yapf'
autocmd FileType go let b:codefmt_formatter='gofmt'
autocmd FileType bash,sh,zsh let b:codefmt_formatter='shfmt'

" =================

" Code format
vnoremap <C-f>l :FormatLines<CR>:LspDocumentRangeFormat<CR>
noremap <C-f>d :FormatCode<CR>:LspDocumentFormat<CR>

" Python isort
autocmd FileType python let g:vim_isort_map = '<C-i>'
autocmd FileType python map <C-i> :Isort<CR>
autocmd FileType python let g:vim_isort_python_version = 'python3'
autocmd FileType python vnoremap <C-f>l <C-i>:FormatLines<CR>:LspDocumentRangeFormat<CR>
autocmd FileType python noremap <C-f>d :Isort<CR>:FormatCode<CR>:LspDocumentFormat<CR>

" NERDTree
map <C-n> :NERDTreeToggle<CR>

" lsp
inoremap <expr> <Tab>   pumvisible() ? "\<C-n>" : "\<Tab>"
inoremap <expr> <S-Tab> pumvisible() ? "\<C-p>" : "\<S-Tab>"
inoremap <expr> <cr>    pumvisible() ? "\<C-y>" : "\<cr>"

" ale
" Use mypy only if it's available on the current virtualenv
let g:ale_python_mypy_executable = 'python -m mypy'

" python line length
augroup filetype_python
  autocmd!
  " highlight characters past column 80
  autocmd FileType python hi Excess ctermbg=Red ctermfg=White guibg=Red
  autocmd FileType python match Excess /\%81v.*/
  autocmd FileType python set nowrap
  autocmd FileType python hi ColorColumn ctermbg=240 ctermfg=White
  autocmd FileType python set colorcolumn=80
  autocmd FileType python set expandtab
augroup END

" indentLine
let g:indentLine_char = '┆'
let g:indentLine_color_term = 243
let g:indentLine_color_gui = '#767676'

" Airline theme
let g:airline_theme='bubblegum'

" Custom
map <Leader>p :set paste<CR>
map <Leader><S-p> :set nopaste<CR>
map <C-j> <C-w>j
map <C-k> <C-w>k
