" setting for encoding
set encoding=utf-8
set fileencoding=utf-8
set fileencodings=ucs-bom,utf-8,cp949,latin1

syntax on " Enable highlighting syntax

set nocp " not compatible with `vi`
set nu " show line numbers
set hls " hightlight search keywords
set ruler " show current cursor location
set history=1000 " history of vim command

set expandtab " softtab(space)
set tabstop=4 " tab size
set sw=4 " tab size: shifting(`<<`, `>>`)
set sts=4 " tab size: shifting(`<<`, `>>`)
set autoindent

" Plugins
call plug#begin('~/.vim/plugged')

Plug 'rhysd/committia.vim'
Plug 'hotwatermorning/auto-git-diff'
Plug 'junegunn/vim-easy-align'
Plug 'w0rp/ale' " Asynchronous Lint Engine
Plug 'scrooloose/nerdtree', { 'on': 'NERDTreeToggle' }  " - NERDTree
Plug 'Valloric/YouCompleteMe' " Auto complete / needed to run `install.py` at first
Plug 'majutsushi/tagbar' " Tag bar
Plug 'vim-scripts/Command-T' " Fast file navigation
Plug 'sheerun/vim-polyglot' " Highlight many languages syntax
Plug 'tpope/vim-commentary' " Add shortcut `gc[c]` to comment out
Plug 'eugen0329/vim-esearch' " Async search and replace
Plug 'devinjeon/leetcode.vim'
Plug 'plasticboy/vim-markdown'
Plug 'hashivim/vim-terraform'

" google/vimcodefmt
Plug 'google/vim-maktaba'
Plug 'google/vim-glaive'
Plug 'google/vim-codefmt'

call plug#end()

" =================
" google/vimcodefmt

autocmd FileType c,cpp,proto let b:codefmt_formatter='clang-format'
autocmd FileType vue,javascript,html,css,sass,scss,less,json let b:codefmt_formatter='prettier'
autocmd FileType python let b:codefmt_formatter='yapf'
autocmd FileType go let b:codefmt_formatter='gofmt'
autocmd FileType bash,sh,zsh let b:codefmt_formatter='shfmt'

" =================

let g:ycm_python_binary_path = 'python'
let g:vim_markdown_folding_disabled = 1
