#!/usr/bin/env zsh
# zmodload zsh/zprof # temp

allstart=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
t=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
accume=0

# Configure the system.
unset GOARCH
unset GOROOT
unset GOPATH
export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_ALL=$LANG
export HISTSIZE=10000000
export SAVEHIST=$HISTSIZE
setopt EXTENDED_HISTORY

export ORIGIN_PATH=$PATH

# NOTE: `*-magic` is known buggy in some zsh versions.
# (see: https://github.com/robbyrussell/oh-my-zsh/blob/e604eaf55/lib/misc.zsh#L3)
#
# The following error message is shown in my Ubuntu environment
# whenever I paste something into my terminal, so I disabled it.
# """
# bracketed-paste-magic:zle:38: not enough arguments for -U
# """
export DISABLE_MAGIC_FUNCTIONS="true"
export DISABLE_AUTO_UPDATE="true"
export DISABLE_COMPFIX="true"

cur=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
echo "cur: $cur" # temp
gap=$((cur - t))
t=$cur
accume=$((accume + gap))
echo "- gap:          $gap sec - pre1" # temp
echo "- accuumulated: $accume sec - pre1" # temp
echo "=========================================" # temp

# Oh My ZSH!
export ZSH=$HOME/.oh-my-zsh
if [[ -d "$ZSH" ]]; then
  plugins=(git z example git-flow-completion zsh-autosuggestions zsh-syntax-highlighting)
  ZSH_THEME="vin"
  source $ZSH/oh-my-zsh.sh
fi

cur=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
gap=$((cur - t))
t=$cur
accume=$((accume + gap))
echo "- gap:          $gap sec - omzsh" # temp
echo "- accuumulated: $accume sec - omzsh" # temp
echo "=========================================" # temp

# Make the completion scripts for bash compatible with zsh
# https://stackoverflow.com/questions/3249432/can-a-bash-tab-completion-script-be-used-in-zsh
autoload bashcompinit && bashcompinit
# Activate rc files
mkdir -p "$HOME/.rc"

cur=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
gap=$((cur - t))
t=$cur
accume=$((accume + gap))
echo "- gap:          $gap sec - bashcompinit" # temp
echo "- accuumulated: $accume sec - bashcompinit" # temp
echo "=========================================" # temp

# sorted rc files
for p in $(find "$HOME/.rc/" -not -type d | sort); do
  source "$p"
  cur=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
  gap=$((cur - t))
  t=$cur
  accume=$((accume + gap))
  echo "- gap:          $gap sec - $p" # temp
  echo "- accuumulated: $accume sec - $p" # temp
  echo "=========================================" # temp
done

export SETUP_COMPLETION=true
# zprof # temp


# Prevent terminal emulator from executing Tmux automatically
# e.g.) TERMINAL_EMULATOR=JetBrains-JediTerm (on IntelliJ)
if [[ -z "$TMUX" && -z "$TERMINAL_EMULATOR" ]]; then
  session="default"
  (tmux has-session -t "$session" && tmux attach -t "$session") || tmux new -s "$session"
else
  # Prevent PATH from being duplicated in Tmux session
  # ref: https://stackoverflow.com/questions/13058578/how-to-prevent-tmux-from-filling-up-the-global-path-variable-with-duplicated-pat
  export PATH=$ORIGIN_PATH
fi

cur=$(gdate +%s%N | awk '{printf "%.6f\n", $1 / 1000000000}') # temp
gap=$((cur - t))
t=$cur
accume=$((accume + gap))
echo "- gap:          $gap sec - tmux" # temp
echo "- accuumulated: $accume sec - tmux" # temp
echo "=========================================" # temp
echo "- all gap:      $((cur - allstart)) sec" # temp
