#!/usr/bin/env zsh

# fzf
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# Activate rc files
mkdir -p "$HOME/.rc"
for p in $(find "$HOME/.rc/" -not -type d)
do
    source "$p"
done

# Configure the system.
export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_ALL=$LANG

# Oh My ZSH!
export ZSH=$HOME/.oh-my-zsh
plugins=(git z)
if [[ -d "$ZSH" ]]
then
  for plugin_path in $ZSH/custom/plugins/*
  do
    plugin="$(basename $plugin_path)"
    if [[ -f "$plugin_path/$plugin.plugin.zsh" ]] \
        && [[ "$plugin" != "zsh-syntax-highlighting" ]]
    then
      plugins+=("$plugin")
    fi
  done
  # `zsh-syntax-highlighting` must be last at plugins
  plugins+=("zsh-syntax-highlighting")

  ZSH_THEME="vin"
  source $ZSH/oh-my-zsh.sh

