#!/usr/bin/env zsh

# fzf
[[ -f ~/.fzf.zsh ]] && source ~/.fzf.zsh

# Activate rc files
mkdir -p "$HOME/.rc"
for p in $(find "$HOME/.rc/" -not -type d)
do
    source "$p"
done

# Configure the system.
export EDITOR="vim"
export LANG="en_US.UTF-8"
export LC_ALL=$LANG

# Oh My ZSH!
export ZSH=$HOME/.oh-my-zsh
plugins=(git z)
if [[ -d "$ZSH" ]]
then
  for plugin_path in $ZSH/custom/plugins/*
  do
    plugin="$(basename $plugin_path)"
    if [[ -f "$plugin_path/$plugin.plugin.zsh" ]] \
        && [[ "$plugin" != "zsh-syntax-highlighting" ]]
    then
      plugins+=("$plugin")
    fi
  done
  # `zsh-syntax-highlighting` must be last at plugins
  plugins+=("zsh-syntax-highlighting")

  ZSH_THEME="vin"
  source $ZSH/oh-my-zsh.sh
  # This speeds up pasting w/ autosuggest
  # https://github.com/zsh-users/zsh-autosuggestions/issues/238
  pasteinit() {
      OLD_SELF_INSERT=${${(s.:.)widgets[self-insert]}[2,3]}
      zle -N self-insert url-quote-magic # I wonder if you'd need `.url-quote-magic`?
  }

  pastefinish() {
      zle -N self-insert $OLD_SELF_INSERT
  }
  zstyle :bracketed-paste-magic paste-init pasteinit
  zstyle :bracketed-paste-magic paste-finish pastefinish
fi
