return {
	{
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		config = function()
			local configs = require("nvim-treesitter.configs")
			configs.setup({
				ensure_installed = {
					"angular",
					"c",
					"cpp",
					"css",
					"csv",
					"cuda",
					"diff",
					"go",
					"gomod",
					"gosum",
					"gotmpl",
					"hcl",
					"html",
					"http",
					"helm",
					"java",
					"javascript",
					"jinja",
					"jinja_inline",
					"jq",
					"json",
					"lua",
					"make",
					"markdown",
					"promql",
					"python",
					"query",
					"ruby",
					"regex",
					"scala",
					"scss",
					"sql",
					"ssh_config",
					"strace",
					"terraform",
					"tmux",
					"toml",
					"tsv",
					"typescript",
					"xml",
					"yaml",
				},
				sync_install = true,
				highlight = { enable = true },
				indent = { enable = true },
				refactor = {
					highlight_definitions = {
						enable = true,
						clear_on_cursor_move = true,
					},
				},
			})
		end,
	},
	{
		"nvim-treesitter/nvim-treesitter-context",
	},
	{
		"nvim-treesitter/nvim-treesitter-refactor",
	},
}
